### PR TITLE
dont allow downvotes optionally

### PR DESCRIPTION
**Pull request by bdelo**

### CODE REVIEW

**Comment by davidbstein** [comment]
I need to do a DB migration before pulling. Adding some react nitpicks but I'll make them when I merge.

**Comment by bdelo** [comment]
💯 If you could add comments and context around react nitpicks too, that'd be helpful. This was the first I've done anything in react really.

**Comment by davidbstein** [comment]
sure thing. Rather than

```
if (test_bool){
 return <div>
    <div> Something repeated </div>
    <div> something optional </div>
  </div>
} else {
  return <div>
    <div> something repeated </div>
  </div>
}
```
We can isolate the conditional render. there's a few ways to do it, good discussion on the react website here: https://facebook.github.io/react/docs/conditional-rendering.html


(I made the recommended change to this branch already https://github.com/davidbstein/moderator/pull/8/commits/c719adff6b11945db4bed9de7dfbaebc9d4ef112 )

**Comment by davidbstein** [comment]
actually, going to hold off on this pending https://github.com/davidbstein/moderator/issues/5

**Comment by davidbstein** [comment]
have a little free time tonight, can clean it up then.

**Pull request closed without merging**
